# -*- coding: utf-8 -*-
"""flow_water.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHpe_RmaB3jvay6V5XZXhtfGVjYXRv_h
"""

!pip install MDAnalysis

from google.colab import drive
drive.mount('/content/drive')

import MDAnalysis as mda
import numpy as np
import matplotlib.pyplot as plt
import os

upper_end = 6.754
lower_end = -6.754
output_file = "flow.dat"

psf_path = '/content/drive/MyDrive/simulacions/04-05-26/equilibration/system.psf'
dcd_path = '/content/drive/MyDrive/simulacions/04-05-26/equilibration/MDequil.dcd'

if os.path.exists(psf_path):
    u = mda.Universe(psf_path, dcd_path)
    wat = u.select_atoms("name OH2")

    def get_status(z_coords):
        status = []
        for z in z_coords:
            if z < lower_end: status.append(-1)
            elif z > upper_end: status.append(1)
            else: status.append(0)
        return np.array(status)

    u.trajectory[0]
    old_status = get_status(wat.positions[:, 2])
    total = 0
    time = []
    instantflow = []

    with open(output_file, "w") as f:
        for ts in u.trajectory[1:]:
            new_status = get_status(wat.positions[:, 2])
            for old, new in zip(old_status, new_status):
                if old != new and old + new != 0:
                    total += new - old
            old_status = new_status.copy()
            time.append(ts.time)
            instantflow.append(total / 2.0)
            f.write(f"{ts.frame} {total / 2.0}\n")

    print(f"Net flow: {total / 2.0}")

    plt.figure(figsize=(8, 5))
    plt.plot(time, instantflow)
    plt.xlabel('Time (ps)')
    plt.ylabel('Accumulated flow')
    plt.grid(True)
    plt.show()